# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1081aab5b6586ebb6942eb8eff05ef12a99230a0974639064f95a7f44a3e407e2e3a974226995758d0ec0f08df9d3001538fcdfa2dbb56ab66ffc0a3126d4191

  facebook_api_key: 1679193349002420
  facebook_api_secret: 10cc446eb904b965f89484e990d4e8de
  #facebook_app_key: 1679193349002420
  #facebook_app_secret: 10cc446eb904b965f89484e990d4e8de

  twitter_api_key: "API KEY"
  twitter_api_secret: "API SECRET"

  google_api_key: "API KEY"
  google_api_secret: "API SECRET"

  linkedin_api_key: "API KEY"
  linkedin_api_secret: "API SECRET"

test:
  secret_key_base: 3e29ef04380c3d21d9f177d110169af431fdf879519ce34ca88efea13e3332a0b86f830ba6da1da245be9aaf4520c6c1728f435142081c526119c6efcf2e1909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
